import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "../components/header";
import PageTransition from "@/components/PageTransition";
// import StairTransition from "@/components/StairTransition";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <ClerkProvider>
            <Header />
            <PageTransition>{children}</PageTransition>
          </ClerkProvider>
        </Providers>
      </body>
    </html>
  );
}
